### ISSUE TITLE
quiz form not adding the questions

### ISSUE THREAD

**Issue by RahiMedouni** [RahiMedouni/book-frontend#4]
@obadacharif 
front-twin\src\Components\bookQuiz\Quiz.js

const [questions, setQuestions] = useState([
    {
      text: "What is the capital of America?",
      options: [
        { id: 0, text: "New York City", isCorrect: false },
        { id: 1, text: "Boston", isCorrect: false },
        { id: 2, text: "Santa Fe", isCorrect: false },
        { id: 3, text: "Washington DC", isCorrect: true },
      ],
    },
])

front-twin\src\Components\bookQuiz\AddQuiz.js

 <div className="col-12">
                <input
                  type="text"
                  className="form-control"
                  placeholder="add question..."
                  onChange={(e) => setQuestion(e.target.value)}
                  value={question}
                />
              </div>
              <div className="col-12">
                <label className="form-label">Option 1:</label>
                <input
                  type="text"
                  className="form-control"
                  placeholder="enter description here"
                  onChange={(e) => setOne(e.target.value)}
                  value={one}
                />
                <input
                  type="checkbox"
                  className="form-check"
                  onChange={(e) => setOne(e.target.value)}
                />

**Comment by obadacharif** [comment]
inside your AddQuiz component you're calling this function 'handleAdd'
But you didn't pass it from the parent !


`const AddQuiz = ({ handleAdd }) => {`

TODO : 

Define the function handleAdd inside the parent component Quiz and pass it as props

**Comment by RahiMedouni** [comment]
i added the fuction, i couldn't figure out how to create the same object from the form add quiz @obadacharif
